class RunTimeOrderException(Exception):
    pass


class FunctionNotFoundException(Exception):
    pass
